// Short interface labels shared by the redesigned public pages.
export const premiumCopy = {
  en: {
    studyGuide: "Study guide",
    studentPortal: "Student portal",
    skipContent: "Skip to content",
    language: "Website language",
    navigation: "Navigation",
    explore: "Explore",
    plan: "Your application plan",
    profile: "Profile review",
    match: "University shortlist",
    application: "Application",
    ready: "First step",
    next: "Up next",
    planned: "Then",
    admissions: "University admissions",
    based: "Based in Istanbul",
    localGuidance: "Guidance shaped by local knowledge.",
    ask: "Ask a question",
    start: "Start an application",
    footerKicker: "Your next chapter can start here.",
    footerTitle: "A new horizon. A plan to get there.",
    journeyTitle: "A clear route from ambition to admission.",
    applied: "Already applied?",
    track: "Follow your application online.",
    checkStatus: "Check application status",
    contactTitle: "Big plans start with a conversation.",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactChannel: "Let’s talk about your future.",
    contactDesc:
      "Tell our team what you want to study and where you are in the process.",
    formKicker: "Your goals. Our starting point.",
    consultation: "Request a consultation",
    subjectExample: "For example: Engineering, undergraduate",
    messageExample: "Your preferred subject, study level, and any questions.",
    privacyNote: "We use your details to respond to your enquiry.",
    privacyLink: "Read our privacy policy",
    stillDeciding: "Still deciding?",
    view: "View",
    community: "Horizon community",
    mediaTitle: "A closer look at the student journey",
    mediaOpen: "Open media",
    mediaPrevious: "Previous media",
    mediaNext: "Next media",
    trust1: "Local perspective",
    trust2: "Clear communication",
    trust3: "One connected journey",
    trust4: "Stay informed",
    value1: "Istanbul-based team",
    value2: "Multilingual support",
    value3: "Application to arrival",
    value4: "Online status tracking",
    step1: "Share your goals, preferred subject, study level, and timeline.",
    step2: "Understand the requirements and prepare your documents.",
    step3: "Compare suitable universities and agree on your shortlist.",
    step4: "Follow decisions and prepare for the next stage.",
  },
  tr: {
    studyGuide: "Eğitim rehberi",
    studentPortal: "Öğrenci portalı",
    skipContent: "İçeriğe geç",
    language: "Site dili",
    navigation: "Gezinme",
    explore: "Keşfet",
    plan: "Başvuru planınız",
    profile: "Profil değerlendirmesi",
    match: "Üniversite seçenekleri",
    application: "Başvuru",
    ready: "İlk adım",
    next: "Sırada",
    planned: "Sonra",
    admissions: "Üniversite başvuruları",
    based: "İstanbul merkezli",
    localGuidance: "Yerel deneyimle şekillenen rehberlik.",
    ask: "Soru sorun",
    start: "Başvuruya başlayın",
    footerKicker: "Yeni bölümünüz burada başlayabilir.",
    footerTitle: "Yeni bir ufuk. Oraya ulaşmak için bir plan.",
    journeyTitle: "Hedeflerinizden üniversiteye açık bir yol.",
    applied: "Başvurdunuz mu?",
    track: "Başvurunuzu çevrimiçi takip edin.",
    checkStatus: "Başvuru durumunu kontrol edin",
    contactTitle: "Büyük planlar bir sohbetle başlar.",
    contactPhone: "Telefon",
    contactEmail: "E-posta",
    contactChannel: "Geleceğiniz hakkında konuşalım.",
    contactDesc:
      "Ne okumak istediğinizi ve sürecin hangi aşamasında olduğunuzu ekibimize anlatın.",
    formKicker: "Hedefleriniz başlangıç noktamız.",
    consultation: "Danışmanlık talep edin",
    subjectExample: "Örneğin: Mühendislik, lisans",
    messageExample: "Tercih ettiğiniz bölüm, eğitim düzeyi ve sorularınız.",
    privacyNote: "Bilgilerinizi talebinize yanıt vermek için kullanırız.",
    privacyLink: "Gizlilik politikamızı okuyun",
    stillDeciding: "Hâlâ karar veriyor musunuz?",
    view: "Görüntüle",
    community: "Horizon topluluğu",
    mediaTitle: "Öğrenci yolculuğuna yakından bakış",
    mediaOpen: "Medyayı aç",
    mediaPrevious: "Önceki medya",
    mediaNext: "Sonraki medya",
    trust1: "Yerel deneyim",
    trust2: "Açık iletişim",
    trust3: "Bütünleşik bir süreç",
    trust4: "Haberdar olun",
    value1: "İstanbul merkezli ekip",
    value2: "Çok dilli destek",
    value3: "Başvurudan varışa",
    value4: "Çevrimiçi durum takibi",
    step1:
      "Hedeflerinizi, bölümünüzü, eğitim düzeyinizi ve takviminizi paylaşın.",
    step2: "Gereklilikleri öğrenin ve belgelerinizi hazırlayın.",
    step3: "Uygun üniversiteleri karşılaştırıp listenizi oluşturun.",
    step4: "Kararları takip edin ve sonraki aşamaya hazırlanın.",
  },
  fr: {
    studyGuide: "Guide des études",
    studentPortal: "Espace étudiant",
    skipContent: "Aller au contenu",
    language: "Langue du site",
    navigation: "Navigation",
    explore: "Découvrir",
    plan: "Votre plan de candidature",
    profile: "Étude du profil",
    match: "Sélection d’universités",
    application: "Candidature",
    ready: "Première étape",
    next: "Ensuite",
    planned: "Puis",
    admissions: "Admissions universitaires",
    based: "Basés à Istanbul",
    localGuidance: "Des conseils nourris par notre connaissance locale.",
    ask: "Poser une question",
    start: "Commencer une candidature",
    footerKicker: "Votre prochain chapitre peut commencer ici.",
    footerTitle: "Un nouvel horizon. Un plan pour y arriver.",
    journeyTitle: "Un parcours clair, de votre ambition à l’admission.",
    applied: "Déjà candidat ?",
    track: "Suivez votre candidature en ligne.",
    checkStatus: "Consulter le statut",
    contactTitle: "Les grands projets commencent par un échange.",
    contactPhone: "Téléphone",
    contactEmail: "E-mail",
    contactChannel: "Parlons de votre avenir.",
    contactDesc:
      "Indiquez à notre équipe ce que vous souhaitez étudier et où vous en êtes.",
    formKicker: "Vos objectifs, notre point de départ.",
    consultation: "Demander un entretien",
    subjectExample: "Par exemple : ingénierie, licence",
    messageExample: "Votre domaine, votre niveau d’études et vos questions.",
    privacyNote:
      "Nous utilisons vos coordonnées pour répondre à votre demande.",
    privacyLink: "Lire notre politique de confidentialité",
    stillDeciding: "Vous hésitez encore ?",
    view: "Voir",
    community: "La communauté Horizon",
    mediaTitle: "Le parcours étudiant de plus près",
    mediaOpen: "Ouvrir le média",
    mediaPrevious: "Média précédent",
    mediaNext: "Média suivant",
    trust1: "Un regard local",
    trust2: "Une communication claire",
    trust3: "Un parcours continu",
    trust4: "Restez informé",
    value1: "Une équipe à Istanbul",
    value2: "Un accompagnement multilingue",
    value3: "De la candidature à l’arrivée",
    value4: "Un suivi en ligne",
    step1:
      "Partagez vos objectifs, votre domaine, votre niveau et votre calendrier.",
    step2: "Comprenez les exigences et préparez vos documents.",
    step3: "Comparez les universités adaptées et établissez votre sélection.",
    step4: "Suivez les décisions et préparez la prochaine étape.",
  },
  fa: {
    studyGuide: "راهنمای تحصیل",
    studentPortal: "پرتال دانشجو",
    skipContent: "رفتن به محتوا",
    language: "زبان وب‌سایت",
    navigation: "راهبری",
    explore: "بیشتر بدانید",
    plan: "برنامه درخواست شما",
    profile: "بررسی سوابق",
    match: "انتخاب دانشگاه",
    application: "درخواست پذیرش",
    ready: "گام نخست",
    next: "گام بعد",
    planned: "سپس",
    admissions: "پذیرش دانشگاه",
    based: "مستقر در استانبول",
    localGuidance: "راهنمایی بر پایه شناخت محلی.",
    ask: "سؤال بپرسید",
    start: "شروع درخواست",
    footerKicker: "فصل بعدی زندگی شما از اینجا آغاز می‌شود.",
    footerTitle: "افقی تازه. برنامه‌ای برای رسیدن به آن.",
    journeyTitle: "مسیری روشن از آرزو تا پذیرش.",
    applied: "قبلاً درخواست داده‌اید؟",
    track: "درخواست خود را آنلاین پیگیری کنید.",
    checkStatus: "بررسی وضعیت درخواست",
    contactTitle: "برنامه‌های بزرگ با گفتگو آغاز می‌شوند.",
    contactPhone: "تلفن",
    contactEmail: "ایمیل",
    contactChannel: "درباره آینده شما گفتگو کنیم.",
    contactDesc:
      "به تیم ما بگویید چه رشته‌ای می‌خواهید بخوانید و در کدام مرحله هستید.",
    formKicker: "اهداف شما، نقطه آغاز ما.",
    consultation: "درخواست مشاوره",
    subjectExample: "مثلاً: مهندسی، کارشناسی",
    messageExample: "رشته و مقطع مورد نظر و سؤالات خود را بنویسید.",
    privacyNote: "از اطلاعات شما برای پاسخ به درخواستتان استفاده می‌کنیم.",
    privacyLink: "سیاست حریم خصوصی ما",
    stillDeciding: "هنوز تصمیم نگرفته‌اید؟",
    view: "مشاهده",
    community: "جامعه هورایزن",
    mediaTitle: "نگاهی نزدیک‌تر به مسیر دانشجو",
    mediaOpen: "باز کردن رسانه",
    mediaPrevious: "رسانه قبلی",
    mediaNext: "رسانه بعدی",
    trust1: "شناخت محلی",
    trust2: "ارتباط روشن",
    trust3: "مسیری پیوسته",
    trust4: "آگاه بمانید",
    value1: "تیم مستقر در استانبول",
    value2: "پشتیبانی چندزبانه",
    value3: "از درخواست تا ورود",
    value4: "پیگیری آنلاین وضعیت",
    step1: "اهداف، رشته، مقطع و زمان‌بندی خود را با ما در میان بگذارید.",
    step2: "شرایط را بشناسید و مدارک خود را آماده کنید.",
    step3: "دانشگاه‌های مناسب را مقایسه و فهرست خود را نهایی کنید.",
    step4: "نتایج را پیگیری و برای مرحله بعد آماده شوید.",
  },
  ar: {
    studyGuide: "دليل الدراسة",
    studentPortal: "بوابة الطالب",
    skipContent: "انتقل إلى المحتوى",
    language: "لغة الموقع",
    navigation: "التنقل",
    explore: "اكتشف",
    plan: "خطة طلبك",
    profile: "مراجعة الملف",
    match: "قائمة الجامعات",
    application: "طلب القبول",
    ready: "الخطوة الأولى",
    next: "التالي",
    planned: "ثم",
    admissions: "القبول الجامعي",
    based: "مقرنا إسطنبول",
    localGuidance: "إرشاد يستند إلى معرفة محلية.",
    ask: "اطرح سؤالاً",
    start: "ابدأ طلبك",
    footerKicker: "قد يبدأ فصلك القادم هنا.",
    footerTitle: "أفق جديد. وخطة للوصول إليه.",
    journeyTitle: "طريق واضح من الطموح إلى القبول.",
    applied: "هل قدمت طلبك؟",
    track: "تابع طلبك عبر الإنترنت.",
    checkStatus: "تحقق من حالة الطلب",
    contactTitle: "الخطط الكبيرة تبدأ بمحادثة.",
    contactPhone: "الهاتف",
    contactEmail: "البريد الإلكتروني",
    contactChannel: "لنتحدث عن مستقبلك.",
    contactDesc: "أخبر فريقنا بما ترغب في دراسته والمرحلة التي وصلت إليها.",
    formKicker: "أهدافك هي نقطة انطلاقنا.",
    consultation: "اطلب استشارة",
    subjectExample: "مثلاً: هندسة، بكالوريوس",
    messageExample: "التخصص والمرحلة الدراسية والأسئلة التي لديك.",
    privacyNote: "نستخدم بياناتك للرد على استفسارك.",
    privacyLink: "اقرأ سياسة الخصوصية",
    stillDeciding: "ما زلت تفكر؟",
    view: "عرض",
    community: "مجتمع هورايزن",
    mediaTitle: "نظرة أقرب إلى رحلة الطالب",
    mediaOpen: "فتح الوسائط",
    mediaPrevious: "الوسائط السابقة",
    mediaNext: "الوسائط التالية",
    trust1: "رؤية محلية",
    trust2: "تواصل واضح",
    trust3: "رحلة متكاملة",
    trust4: "ابقَ مطلعاً",
    value1: "فريق في إسطنبول",
    value2: "دعم متعدد اللغات",
    value3: "من الطلب إلى الوصول",
    value4: "متابعة الحالة إلكترونياً",
    step1: "شارك أهدافك وتخصصك ومستواك الدراسي وجدولك الزمني.",
    step2: "تعرّف على المتطلبات وجهّز مستنداتك.",
    step3: "قارن الجامعات المناسبة وحدد قائمتك.",
    step4: "تابع القرارات واستعد للمرحلة التالية.",
  },
  ps: {
    studyGuide: "د زده کړو لارښود",
    studentPortal: "د محصل پورټل",
    skipContent: "منځپانګې ته لاړ شئ",
    language: "د وېبپاڼې ژبه",
    navigation: "لارموندنه",
    explore: "نور وګورئ",
    plan: "ستاسو د غوښتنلیک پلان",
    profile: "د معلوماتو ارزونه",
    match: "د پوهنتونونو لېست",
    application: "غوښتنلیک",
    ready: "لومړی ګام",
    next: "بل ګام",
    planned: "وروسته",
    admissions: "د پوهنتون داخله",
    based: "په استانبول کې",
    localGuidance: "د سیمه‌ییزې پوهې پر بنسټ لارښوونه.",
    ask: "پوښتنه وکړئ",
    start: "غوښتنلیک پیل کړئ",
    footerKicker: "ستاسو نوی پړاو له دې ځایه پیلېدای شي.",
    footerTitle: "نوی افق. ورته د رسېدو پلان.",
    journeyTitle: "له هیلې تر داخلې روښانه لار.",
    applied: "غوښتنلیک مو سپارلی؟",
    track: "خپل غوښتنلیک آنلاین تعقیب کړئ.",
    checkStatus: "د غوښتنلیک حالت وګورئ",
    contactTitle: "لوی پلانونه په خبرو پیلېږي.",
    contactPhone: "ټیلیفون",
    contactEmail: "برېښنالیک",
    contactChannel: "ستاسو د راتلونکي په اړه وغږېږو.",
    contactDesc:
      "زموږ ټیم ته ووایئ چې څه زده کول غواړئ او په کوم پړاو کې یاست.",
    formKicker: "ستاسو موخې، زموږ د پیل ټکی.",
    consultation: "د مشورې غوښتنه",
    subjectExample: "د بېلګې په توګه: انجنیري، لیسانس",
    messageExample: "د خوښې څانګه، د زده کړو کچه او خپلې پوښتنې ولیکئ.",
    privacyNote: "ستاسو معلومات ستاسو پوښتنې ته د ځواب لپاره کاروو.",
    privacyLink: "د محرمیت تګلاره ولولئ",
    stillDeciding: "لا پرېکړه کوئ؟",
    view: "وګورئ",
    community: "د هورایزن ټولنه",
    mediaTitle: "د محصل سفر ته نږدې کتنه",
    mediaOpen: "انځور یا ویډیو پرانیزئ",
    mediaPrevious: "مخکینی انځور یا ویډیو",
    mediaNext: "راتلونکی انځور یا ویډیو",
    trust1: "سیمه‌ییزه پوهه",
    trust2: "روښانه اړیکې",
    trust3: "یو تړلی سفر",
    trust4: "خبر پاتې شئ",
    value1: "په استانبول کې ټیم",
    value2: "څو ژبنی ملاتړ",
    value3: "له غوښتنلیک تر راتګ",
    value4: "د حالت آنلاین تعقیب",
    step1: "خپلې موخې، څانګه، کچه او مهال‌وېش شریک کړئ.",
    step2: "شرایط وپېژنئ او خپل اسناد چمتو کړئ.",
    step3: "مناسب پوهنتونونه پرتله او خپل لېست جوړ کړئ.",
    step4: "پرېکړې تعقیب او بل پړاو ته چمتو شئ.",
  },
  ur: {
    studyGuide: "تعلیمی رہنما",
    studentPortal: "طالب علم پورٹل",
    skipContent: "مواد پر جائیں",
    language: "ویب سائٹ کی زبان",
    navigation: "رہنمائی",
    explore: "مزید دیکھیں",
    plan: "آپ کی درخواست کا منصوبہ",
    profile: "پروفائل کا جائزہ",
    match: "جامعات کی فہرست",
    application: "درخواست",
    ready: "پہلا قدم",
    next: "اگلا قدم",
    planned: "پھر",
    admissions: "جامعہ میں داخلہ",
    based: "استنبول میں قائم",
    localGuidance: "مقامی تجربے پر مبنی رہنمائی۔",
    ask: "سوال پوچھیں",
    start: "درخواست شروع کریں",
    footerKicker: "آپ کا اگلا باب یہاں شروع ہو سکتا ہے۔",
    footerTitle: "نیا افق۔ وہاں پہنچنے کا منصوبہ۔",
    journeyTitle: "خواہش سے داخلے تک واضح راستہ۔",
    applied: "درخواست دے چکے ہیں؟",
    track: "اپنی درخواست آن لائن دیکھیں۔",
    checkStatus: "درخواست کی حیثیت دیکھیں",
    contactTitle: "بڑے منصوبے گفتگو سے شروع ہوتے ہیں۔",
    contactPhone: "فون",
    contactEmail: "ای میل",
    contactChannel: "آپ کے مستقبل پر بات کرتے ہیں۔",
    contactDesc:
      "ہماری ٹیم کو بتائیں کہ آپ کیا پڑھنا چاہتے ہیں اور کس مرحلے پر ہیں۔",
    formKicker: "آپ کے مقاصد، ہماری شروعات۔",
    consultation: "مشاورت کی درخواست",
    subjectExample: "مثلاً: انجینئرنگ، بیچلر",
    messageExample: "اپنا پسندیدہ مضمون، تعلیمی سطح اور سوالات لکھیں۔",
    privacyNote:
      "ہم آپ کی معلومات آپ کی درخواست کا جواب دینے کے لیے استعمال کرتے ہیں۔",
    privacyLink: "رازداری کی پالیسی پڑھیں",
    stillDeciding: "ابھی فیصلہ کر رہے ہیں؟",
    view: "دیکھیں",
    community: "ہورائزن کمیونٹی",
    mediaTitle: "طالب علم کے سفر پر ایک نظر",
    mediaOpen: "میڈیا کھولیں",
    mediaPrevious: "پچھلا میڈیا",
    mediaNext: "اگلا میڈیا",
    trust1: "مقامی تجربہ",
    trust2: "واضح رابطہ",
    trust3: "ایک مربوط سفر",
    trust4: "باخبر رہیں",
    value1: "استنبول میں ٹیم",
    value2: "کئی زبانوں میں معاونت",
    value3: "درخواست سے آمد تک",
    value4: "آن لائن حیثیت کی نگرانی",
    step1: "اپنے مقاصد، مضمون، تعلیمی سطح اور وقت کا منصوبہ بتائیں۔",
    step2: "شرائط جانیں اور اپنی دستاویزات تیار کریں۔",
    step3: "مناسب جامعات کا موازنہ کر کے فہرست بنائیں۔",
    step4: "فیصلے دیکھیں اور اگلے مرحلے کی تیاری کریں۔",
  },
  hi: {
    studyGuide: "अध्ययन मार्गदर्शिका",
    studentPortal: "छात्र पोर्टल",
    skipContent: "मुख्य सामग्री पर जाएँ",
    language: "वेबसाइट की भाषा",
    navigation: "नेविगेशन",
    explore: "और जानें",
    plan: "आपकी आवेदन योजना",
    profile: "प्रोफ़ाइल समीक्षा",
    match: "विश्वविद्यालयों की सूची",
    application: "आवेदन",
    ready: "पहला कदम",
    next: "अगला कदम",
    planned: "फिर",
    admissions: "विश्वविद्यालय प्रवेश",
    based: "इस्तांबुल में स्थित",
    localGuidance: "स्थानीय अनुभव पर आधारित मार्गदर्शन।",
    ask: "सवाल पूछें",
    start: "आवेदन शुरू करें",
    footerKicker: "आपका अगला अध्याय यहाँ शुरू हो सकता है।",
    footerTitle: "एक नया क्षितिज। वहाँ पहुँचने की योजना।",
    journeyTitle: "आपकी महत्वाकांक्षा से प्रवेश तक स्पष्ट रास्ता।",
    applied: "पहले से आवेदन किया है?",
    track: "अपने आवेदन की स्थिति ऑनलाइन देखें।",
    checkStatus: "आवेदन की स्थिति देखें",
    contactTitle: "बड़ी योजनाएँ बातचीत से शुरू होती हैं।",
    contactPhone: "फ़ोन",
    contactEmail: "ईमेल",
    contactChannel: "आपके भविष्य के बारे में बात करें।",
    contactDesc:
      "हमारी टीम को बताएँ कि आप क्या पढ़ना चाहते हैं और किस चरण पर हैं।",
    formKicker: "आपके लक्ष्य, हमारी शुरुआत।",
    consultation: "परामर्श का अनुरोध करें",
    subjectExample: "उदाहरण: इंजीनियरिंग, स्नातक",
    messageExample: "अपना पसंदीदा विषय, अध्ययन स्तर और सवाल बताएँ।",
    privacyNote:
      "हम आपके विवरण का उपयोग आपके सवाल का जवाब देने के लिए करते हैं।",
    privacyLink: "हमारी गोपनीयता नीति पढ़ें",
    stillDeciding: "अभी भी सोच रहे हैं?",
    view: "देखें",
    community: "होराइज़न समुदाय",
    mediaTitle: "छात्र की यात्रा को करीब से जानें",
    mediaOpen: "मीडिया खोलें",
    mediaPrevious: "पिछला मीडिया",
    mediaNext: "अगला मीडिया",
    trust1: "स्थानीय अनुभव",
    trust2: "स्पष्ट संवाद",
    trust3: "एक जुड़ी हुई यात्रा",
    trust4: "सूचित रहें",
    value1: "इस्तांबुल में टीम",
    value2: "बहुभाषी सहायता",
    value3: "आवेदन से आगमन तक",
    value4: "ऑनलाइन स्थिति देखें",
    step1: "अपने लक्ष्य, विषय, अध्ययन स्तर और समय की योजना बताएँ।",
    step2: "आवश्यकताएँ समझें और दस्तावेज़ तैयार करें।",
    step3: "उपयुक्त विश्वविद्यालयों की तुलना कर सूची बनाएँ।",
    step4: "निर्णयों पर नज़र रखें और अगले चरण की तैयारी करें।",
  },
};

const universityLabels = {
  en: [
    "Find a university. Shape your future.",
    "Explore universities across Türkiye and build a shortlist around the place you want to be.",
    "University profile",
    "Official resources",
    "Explore university",
    "Different cities. Different possibilities. A future that is yours.",
    "Explore all universities",
  ],
  tr: [
    "Üniversitenizi bulun. Geleceğinizi şekillendirin.",
    "Türkiye genelindeki üniversiteleri keşfedin ve hedeflerinize göre bir liste oluşturun.",
    "Üniversite profili",
    "Resmî kaynaklar",
    "Üniversiteyi keşfet",
    "Farklı şehirler. Farklı olanaklar. Size ait bir gelecek.",
    "Tüm üniversiteler",
  ],
  fr: [
    "Trouvez votre université. Dessinez votre avenir.",
    "Découvrez des universités en Türkiye et construisez une sélection adaptée à vos projets.",
    "Profil universitaire",
    "Sources officielles",
    "Découvrir l’université",
    "Des villes et des possibilités différentes. Un avenir qui vous appartient.",
    "Toutes les universités",
  ],
  fa: [
    "دانشگاه خود را پیدا کنید. آینده خود را بسازید.",
    "دانشگاه‌های ترکیه را بشناسید و متناسب با اهداف خود فهرستی تهیه کنید.",
    "معرفی دانشگاه",
    "منابع رسمی",
    "آشنایی با دانشگاه",
    "شهرهای متفاوت. فرصت‌های متفاوت. آینده‌ای از آن شما.",
    "همه دانشگاه‌ها",
  ],
  ar: [
    "اعثر على جامعتك. اصنع مستقبلك.",
    "اكتشف الجامعات في أنحاء تركيا واختر ما يناسب أهدافك.",
    "نبذة عن الجامعة",
    "مصادر رسمية",
    "اكتشف الجامعة",
    "مدن مختلفة. فرص مختلفة. مستقبل يخصك.",
    "جميع الجامعات",
  ],
  ps: [
    "خپل پوهنتون ومومئ. راتلونکی مو جوړ کړئ.",
    "د ترکیې پوهنتونونه وپېژنئ او د خپلو موخو له مخې لېست جوړ کړئ.",
    "د پوهنتون پېژندنه",
    "رسمي سرچینې",
    "پوهنتون وپېژنئ",
    "بېلابېل ښارونه. بېلابېل فرصتونه. ستاسو راتلونکی.",
    "ټول پوهنتونونه",
  ],
  ur: [
    "اپنی جامعہ تلاش کریں۔ اپنا مستقبل بنائیں۔",
    "ترکیہ کی جامعات دیکھیں اور اپنے مقاصد کے مطابق فہرست بنائیں۔",
    "جامعہ کا تعارف",
    "سرکاری ذرائع",
    "جامعہ کے بارے میں جانیں",
    "مختلف شہر۔ مختلف مواقع۔ آپ کا اپنا مستقبل۔",
    "تمام جامعات",
  ],
  hi: [
    "अपना विश्वविद्यालय खोजें। अपना भविष्य बनाएँ।",
    "तुर्किये के विश्वविद्यालयों को जानें और अपने लक्ष्यों के अनुसार सूची बनाएँ।",
    "विश्वविद्यालय परिचय",
    "आधिकारिक स्रोत",
    "विश्वविद्यालय के बारे में जानें",
    "अलग शहर। अलग संभावनाएँ। आपका अपना भविष्य।",
    "सभी विश्वविद्यालय",
  ],
};
const universityKeys = [
  "universitiesTitle",
  "universitiesDesc",
  "universityProfile",
  "officialResources",
  "exploreUniversity",
  "universityClosing",
  "exploreAllUniversities",
];
for (const [language, values] of Object.entries(universityLabels)) {
  universityKeys.forEach((key, index) => {
    premiumCopy[language][key] = values[index];
  });
}

const mediaStateLabels = {
  en: ["Loading student stories…", "We couldn’t load the student stories. Please try again.", "Try again", "New student stories will appear here soon."],
  tr: ["Öğrenci hikâyeleri yükleniyor…", "Öğrenci hikâyeleri yüklenemedi. Lütfen yeniden deneyin.", "Yeniden dene", "Yeni öğrenci hikâyeleri yakında burada olacak."],
  fr: ["Chargement des parcours étudiants…", "Les parcours étudiants n’ont pas pu être chargés. Veuillez réessayer.", "Réessayer", "De nouveaux parcours étudiants seront bientôt présentés ici."],
  fa: ["در حال بارگذاری داستان‌های دانشجویان…", "داستان‌های دانشجویان بارگذاری نشد. لطفاً دوباره تلاش کنید.", "تلاش دوباره", "داستان‌های جدید دانشجویان به‌زودی اینجا منتشر می‌شود."],
  ar: ["جارٍ تحميل قصص الطلاب…", "تعذر تحميل قصص الطلاب. يرجى المحاولة مرة أخرى.", "حاول مرة أخرى", "ستظهر قصص طلاب جديدة هنا قريباً."],
  ps: ["د محصلینو کیسې پورته کېږي…", "د محصلینو کیسې پورته نه شوې. مهرباني وکړئ بیا هڅه وکړئ.", "بیا هڅه وکړئ", "د محصلینو نوې کیسې به ژر دلته خپرې شي."],
  ur: ["طلبہ کی کہانیاں لوڈ ہو رہی ہیں…", "طلبہ کی کہانیاں لوڈ نہیں ہو سکیں۔ براہِ کرم دوبارہ کوشش کریں۔", "دوبارہ کوشش کریں", "طلبہ کی نئی کہانیاں جلد یہاں پیش کی جائیں گی۔"],
  hi: ["छात्रों की कहानियाँ लोड हो रही हैं…", "छात्रों की कहानियाँ लोड नहीं हो सकीं। कृपया दोबारा कोशिश करें।", "दोबारा कोशिश करें", "छात्रों की नई कहानियाँ जल्द यहाँ दिखाई देंगी।"],
};
const mediaStateKeys = ["mediaLoading", "mediaUnavailable", "mediaRetry", "mediaEmpty"];
for (const [language, values] of Object.entries(mediaStateLabels)) {
  mediaStateKeys.forEach((key, index) => {
    premiumCopy[language][key] = values[index];
  });
}
