// Editorial directory. These are study options, not a claim of university affiliation.
// Official source links were reviewed on 16 September 2026. Intake-specific details
// remain with each university so expired fees, dates or quotas are not presented as current.
export const universities = [
  {
    slug: 'ankara-yildirim-beyazit-university',
    name: 'Ankara Yıldırım Beyazıt University',
    shortName: 'AYBU',
    city: 'Ankara',
    logo: '/images/universities/ankara-yildirim-beyazit-university.svg',
    introduction: 'Explore an Ankara university with dedicated information for international applicants. Its Student Affairs office explains application routes, campus information and the steps after admission.',
    admissionsNote: 'Review the international admissions guide and the requirements for your chosen department. Campus and language requirements should be checked at program level.',
    officialUrl: 'https://www.aybu.edu.tr/',
    admissionsUrl: 'https://www.aybu.edu.tr/oidb/en/sayfa/1264',
    sourceLabel: 'International student information',
  },
  {
    slug: 'anadolu-university',
    name: 'Anadolu University',
    shortName: 'Anadolu',
    city: 'Eskişehir',
    logo: '/images/universities/anadolu-university.svg',
    introduction: 'Consider university life in Eskişehir. Anadolu publishes a dedicated international admissions calendar, program quotas and application conditions for its on-campus associate and bachelor’s degrees.',
    admissionsNote: 'Choose the correct route for on-campus study. Open education and on-campus programs have different application processes and study arrangements.',
    officialUrl: 'https://www.anadolu.edu.tr/en',
    admissionsUrl: 'https://oidb.anadolu.edu.tr/en/international-students/application-procedures',
    sourceLabel: 'International application procedures',
  },
  {
    slug: 'izmir-katip-celebi-university',
    name: 'İzmir Katip Çelebi University',
    shortName: 'İKÇÜ',
    city: 'İzmir',
    logo: '/images/universities/izmir-katip-celebi-university.png',
    introduction: 'Discover a study option in İzmir. The university’s international student office publishes application announcements, guides and results for associate and undergraduate applicants.',
    admissionsNote: 'Read the current application guide for accepted qualifications, program choices and the documents required for your intake.',
    officialUrl: 'https://ikcu.edu.tr/',
    admissionsUrl: 'https://intikc.ikcu.edu.tr/',
    sourceLabel: 'International student office',
  },
  {
    slug: 'mersin-university',
    name: 'Mersin University',
    shortName: 'MEÜ',
    city: 'Mersin',
    logo: '/images/universities/mersin-university.svg',
    introduction: 'Explore university study in Mersin. Its international student resources cover accepted exams, language requirements and the application process.',
    admissionsNote: 'Teaching is in Turkish except for programs with partial or full foreign-language instruction. Check the current quota table for the language of your chosen program.',
    officialUrl: 'https://www.mersin.edu.tr/',
    admissionsUrl: 'https://oidb.mersin.edu.tr/idari/ogrenci-isleri-daire-baskanligi/international-students/faq',
    sourceLabel: 'International student questions and answers',
  },
  {
    slug: 'ondokuz-mayis-university',
    name: 'Ondokuz Mayıs University',
    shortName: 'OMÜ',
    city: 'Samsun',
    logo: '/images/universities/ondokuz-mayis-university.png',
    introduction: 'Explore a university in Samsun with a dedicated International Student Office. Its official resources include admissions guides, accepted exam criteria and registration information.',
    admissionsNote: 'Review the current guide, exam criteria and application calendar together. Each announced application period has its own dates.',
    officialUrl: 'https://www.omu.edu.tr/en',
    admissionsUrl: 'https://iso.omu.edu.tr/en',
    sourceLabel: 'International Student Office',
  },
  {
    slug: 'duzce-university',
    name: 'Düzce University',
    shortName: 'DÜ',
    city: 'Düzce',
    logo: '/images/universities/duzce-university.svg',
    introduction: 'Discover a study option in Düzce. Its international student office brings together the application guide, accepted exams, quotas, tuition information and registration steps.',
    admissionsNote: 'Use the university’s international admissions pages to confirm eligibility, accepted scores and the documents required for final registration.',
    officialUrl: 'https://duzce.edu.tr/',
    admissionsUrl: 'https://uluslararasiogrenci.duzce.edu.tr/',
    sourceLabel: 'International student office',
  },
  {
    slug: 'kastamonu-university',
    name: 'Kastamonu University',
    shortName: 'KÜ',
    city: 'Kastamonu',
    logo: '/images/universities/kastamonu-university.jpg',
    introduction: 'Explore university study in Kastamonu. The International Student Coordinatorship is the official starting point for international application information and announcements.',
    admissionsNote: 'Check the latest university announcements and application guide before preparing your program preferences and documents.',
    officialUrl: 'https://www.kastamonu.edu.tr/',
    admissionsUrl: 'https://iso.kastamonu.edu.tr/',
    sourceLabel: 'International Student Coordinatorship',
  },
  {
    slug: 'usak-university',
    name: 'Uşak University',
    shortName: 'UŞAK',
    city: 'Uşak',
    logo: '/images/universities/usak-university.png',
    introduction: 'Consider a university in Uşak. Its international admissions office provides application criteria, registration dates, document guidance and information about Turkish proficiency.',
    admissionsNote: 'Accepted qualifications can differ by program. Check the current admissions announcement for the requirements that apply to your intended degree.',
    officialUrl: 'https://www.usak.edu.tr/',
    admissionsUrl: 'https://admission.usak.edu.tr/',
    sourceLabel: 'International Student Coordinatorship',
  },
  {
    slug: 'zonguldak-bulent-ecevit-university',
    name: 'Zonguldak Bülent Ecevit University',
    shortName: 'BEUN',
    city: 'Zonguldak',
    logo: '/images/universities/zonguldak-bulent-ecevit-university.png',
    introduction: 'Explore a university in Zonguldak. The International Student Office provides a detailed pathway through application, evaluation, registration and language proficiency requirements.',
    admissionsNote: 'Read the program quotas and their specific conditions alongside the accepted exam tables and registration calendar.',
    officialUrl: 'https://w3.beun.edu.tr/',
    admissionsUrl: 'https://isoen.beun.edu.tr/',
    sourceLabel: 'International Student Office',
  },
  {
    slug: 'burdur-mehmet-akif-ersoy-university',
    name: 'Burdur Mehmet Akif Ersoy University',
    shortName: 'MAKÜ',
    city: 'Burdur',
    logo: '/images/universities/burdur-mehmet-akif-ersoy-university.png',
    introduction: 'Discover a study option in Burdur. The university publishes international admission announcements and registration instructions through its official website.',
    admissionsNote: 'Check the current announcement for the application process, original document requirements and Turkish language preparation.',
    officialUrl: 'https://www.mehmetakif.edu.tr/',
    admissionsUrl: 'https://www.mehmetakif.edu.tr/en/content/13117/1/international-student-admission-results-2026-2027-akademic-yili-uluslararasi-1-ogrenci-basvuru-sonuclari-ve-online-kayit-duyurusu',
    sourceLabel: 'International student registration information',
  },
  {
    slug: 'adiyaman-university',
    name: 'Adıyaman University',
    shortName: 'ADYÜ',
    city: 'Adıyaman',
    logo: '/images/universities/adiyaman-university.png',
    introduction: 'Explore university study in Adıyaman. Its International Student Coordinatorship publishes application announcements, placement results and registration guidance.',
    admissionsNote: 'Use the official university application route and review its current guidance on applications and payments. Horizon provides independent guidance; admission decisions are made by the university.',
    officialUrl: 'https://adiyaman.edu.tr/',
    admissionsUrl: 'https://international.adiyaman.edu.tr/',
    sourceLabel: 'International Student Coordinatorship',
  },
  {
    slug: 'kirikkale-university',
    name: 'Kırıkkale University',
    shortName: 'KKÜ',
    city: 'Kırıkkale',
    logo: '/images/universities/kirikkale-university.svg',
    introduction: 'Consider a university in Kırıkkale. The official university website provides access to Student Affairs and the International Office for questions about studying there.',
    admissionsNote: 'Contact the university through its official channels to confirm the current international admissions process and the requirements of your intended program.',
    officialUrl: 'https://en.kku.edu.tr/',
    admissionsUrl: 'https://en.kku.edu.tr/Idari/Sayfa/Index?Sayfa=Contact',
    sourceLabel: 'Official university contact information',
  },
  {
    slug: 'karabuk-university',
    name: 'Karabük University',
    shortName: 'KBÜ',
    city: 'Karabük',
    logo: null,
    introduction: 'Discover university study in Karabük. Its International Students Office publishes separate guidance for associate, undergraduate and graduate applications.',
    admissionsNote: 'Choose the application system that matches your degree level and confirm the registration instructions in the current university announcement.',
    officialUrl: 'https://www.karabuk.edu.tr/',
    admissionsUrl: 'https://iso.karabuk.edu.tr/en',
    sourceLabel: 'International Students Office',
  },
];

export const universityCities = [...new Set(universities.map((university) => university.city))]
  .sort((a, b) => a.localeCompare(b, 'en'));

export function getUniversity(slug) {
  return universities.find((university) => university.slug === slug);
}

export function universityApplicationUrl(university) {
  return `/apply?uni=${encodeURIComponent(university.name)}`;
}
